---

- name: Update yum cache and Install ruby-build dependencies
  yum: pkg={{ item }} state=present update_cache=yes
  become: true
  with_items:
    - bzip2
    - gcc
    - gdbm-devel
    - libffi-devel
    - libyaml-devel
    - ncurses-devel
    - openssl-devel
    - readline-devel
    - zlib-devel